blank_issues_enabled: false
contact_links:
  - name: Feature request
    url: https://github.com/malico/teams/pulls
    about: "For ideas or feature requests, send in a pull request"
  - name: Documentation issue
    url: https://github.com/malico/teams-docs
    about: For documentation issues, open a pull request at the malico/teams-docs repository
